"""
PDF generation and form filling service
"""
from typing import Dict
from pathlib import Path
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from PyPDF2 import PdfReader, PdfWriter
import os

from app.utils.logger import logger


class PDFService:
    """Service for PDF generation and form filling"""

    def __init__(self):
        """Initialize PDF service"""
        self.templates_dir = Path("templates")
        self.templates_dir.mkdir(exist_ok=True)

    def fill_pdf_form(self, form_type: str, fields: Dict[str, str]) -> bytes:
        """
        Fill a PDF form with provided data

        Args:
            form_type: Type of form template to use
            fields: Dictionary of field names to values

        Returns:
            Filled PDF as bytes
        """
        # Always generate a new PDF with filled values
        # In production, you would check for real form templates here
        logger.info(f"Generating filled PDF for form_type={form_type}")
        return self._generate_simple_pdf(fields)

    def _fill_existing_form(self, template_path: Path, fields: Dict[str, str]) -> bytes:
        """
        Fill an existing PDF form

        Args:
            template_path: Path to PDF template
            fields: Field values

        Returns:
            Filled PDF as bytes
        """
        reader = PdfReader(str(template_path))
        writer = PdfWriter()

        # Copy pages
        for page in reader.pages:
            writer.add_page(page)

        # Try to fill form fields if they exist
        if "/AcroForm" in reader.trailer["/Root"]:
            writer.update_page_form_field_values(writer.pages[0], fields)

        # Write to bytes
        output = BytesIO()
        writer.write(output)
        output.seek(0)

        return output.read()

    def _generate_simple_pdf(self, fields: Dict[str, str]) -> bytes:
        """
        Generate a simple PDF with field values filled in

        Args:
            fields: Dictionary of field names to values

        Returns:
            PDF as bytes
        """
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # Add title with border
        c.setFont("Helvetica-Bold", 18)
        c.drawString(180, height - 60, "Personal Information Form")
        c.line(50, height - 70, width - 50, height - 70)

        # Add fields with actual values
        c.setFont("Helvetica", 12)
        y_position = height - 120

        # Define standard field order for better presentation
        field_order = ["full_name", "dob", "date_of_birth", "address", "id_number", "expiry_date"]

        # Create ordered fields dict
        ordered_fields = {}
        for field in field_order:
            if field in fields:
                ordered_fields[field] = fields[field]

        # Add any remaining fields not in the order
        for field_name, field_value in fields.items():
            if field_name not in ordered_fields:
                ordered_fields[field_name] = field_value

        for field_name, field_value in ordered_fields.items():
            if y_position < 100:
                c.showPage()
                y_position = height - 50

            # Format field name nicely
            display_name = field_name.replace("_", " ").title()
            if display_name == "Dob":
                display_name = "Date of Birth"

            # Draw field label (bold)
            c.setFont("Helvetica-Bold", 12)
            c.drawString(70, y_position, f"{display_name}:")

            # Draw field value (regular)
            c.setFont("Helvetica", 11)
            value_text = str(field_value) if field_value else "N/A"

            # Handle long text (like addresses)
            if len(value_text) > 60:
                # Split into multiple lines
                words = value_text.split()
                line = ""
                value_y = y_position
                for word in words:
                    if len(line + word) < 60:
                        line += word + " "
                    else:
                        c.drawString(270, value_y, line.strip())
                        value_y -= 15
                        line = word + " "
                if line:
                    c.drawString(270, value_y, line.strip())
                y_position = value_y - 20
            else:
                c.drawString(270, y_position, value_text)
                y_position -= 35

        # Add footer
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(50, 50, f"Generated by PII Extraction Service")
        c.drawString(50, 35, "This document contains auto-filled information from extracted data")

        c.save()
        buffer.seek(0)

        return buffer.read()

    def create_sample_template(self) -> None:
        """Create a sample PDF template for testing"""
        template_path = self.templates_dir / "sample_form.pdf"

        if template_path.exists():
            return

        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # Create a simple form template
        c.setFont("Helvetica-Bold", 18)
        c.drawString(200, height - 50, "Sample Application Form")

        c.setFont("Helvetica", 12)
        y_pos = height - 100

        fields_layout = [
            ("Full Name:", 120),
            ("Date of Birth:", 140),
            ("Address:", 160),
            ("ID Number:", 180),
            ("Expiry Date:", 200),
        ]

        for label, offset in fields_layout:
            c.drawString(50, height - offset, label)
            c.line(200, height - offset, 500, height - offset)

        c.save()
        buffer.seek(0)

        # Save template
        with open(template_path, "wb") as f:
            f.write(buffer.read())

        logger.info(f"Created sample template at {template_path}")


# Global service instance
pdf_service = PDFService()
